version: "3.9"
services:
  deep-research:
    image: ghcr.io/yzcaiai/deep-think:latest
    pull_policy: always
    container_name: deep-research
    env_file:
      - .env
    ports:
      - "3333:3000"
