services:
  deep-research:
    image: ghcr.io/yzcaiai/deep-think:latest
    pull_policy: always
    container_name: deep-research
    env_file:
      - .env
    ports:
      - "127.0.0.1:3333:3000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
